name: Test ft_printf MacOs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: make re
      run: make re
    - name: curl tester
      run: git clone git@github.com:joppiesaus/ft_printf-tester.git
