name: Test ft_printf MacOs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: make re - ft_printf
      run: make re
    - name: Clone tester
      run: git clone https://github.com/Tripouille/printfTester.git
    - name: Set Term
      run: export TERM=gnome-2007
    - name: run - printfTester
      run: make -C printfTester
